# Setup
title:               O/ I Speak here
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             'ishaanbhatnagar25.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ishaan Bhatnagar
  url:               https://twitter.com/IshaanB25
  email:             ishaanbhatnagar881@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
