# Setup
title:               Ishaa Bhatnagar
tagline:             'A Jekyll theme'
description:         'O/ I Speak here ¯\_(ツ)_/¯'
url:                 https://ishaanbhatnagar25.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ishaan Bhatnagar
  url:               https://twitter.com/IshaanB25
  email:             ishaanbhatnagar881@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
